# SESSION - 1

#### TASK - 1

In [1]:
# 1.Install NumPy in your Python environment using pip, then create a Python file called insta_likes.py and import numpy as np at the top.
#done in classroom

#### TASK -2

In [4]:
# 2.Create a NumPy array called followers using np.array() that stores the follower counts for 5 Instagram influencers: [1200, 15000, 67000, 340000, 1250000]. Print the array, its shape, number of dimensions, and data type.
import numpy as np
followers = np.array([1200,15000,67000,340000,1250000])
followers

array([   1200,   15000,   67000,  340000, 1250000])

In [5]:
followers.shape

(5,)

In [7]:
followers.ndim

1

In [11]:
followers.dtype

dtype('int64')

#### TASK - 3

In [13]:
# 3.Use np.arange() to generate an array of order IDs for 10 consecutive Zomato orders starting from 101. Print the array and its size.
import numpy as np
order_ids  = np.arange(101,111)
order_ids

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [14]:
order_ids.size

10

#### TASK - 4

In [18]:
# 4.Create a 3x3 NumPy array using np.eye() to represent a 'like' identity matrix for a new Spotify playlist feature. Print the matrix and explain what the diagonal values represent in a comment.
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.diag(a)

array([1., 1., 1.])

In [21]:
b = np.matrix(a)
b

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

#### TASK - 5

In [23]:
# 5.Convert a Python list of cricket scores [45, 67, 120, 89, 54] to a NumPy array, then use the .itemsize attribute to print how many bytes each score takes in memory.<br><br><em><strong>Hint:</strong> Use np.array() for conversion and .itemsize for memory size.</em>
cricket_scores = [45, 67, 120, 89, 54]
a = np.array(cricket_scores)
a

array([ 45,  67, 120,  89,  54])

In [24]:
a.itemsize

8

# SESSION - 2

#### TASK - 1

In [25]:
# 1.Create a 2D NumPy array representing the ratings (out of 5) given by 4 users to 5 different food items on Zomato. Use slicing to extract the ratings given by the second and third users only.
a = np.array([[1,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7],[4,5,6,7,8]])
a

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [26]:
b = a[1:3]
b

array([[2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

####TASK - 2

In [27]:
# 2.Given a NumPy array of daily steps tracked for 10 days, use boolean indexing to select only the days where the steps were greater than 8000.<br><br><em><strong>Hint:</strong> Use an array like steps = np.array([7500, 8200, 9000, ...]) and apply a boolean condition.</em>
steps = np.array([7500, 8200, 9000,9500,3000,4000,30000,40000,7400,3500])
filtered_steps = steps[steps > 8000]
print(filtered_steps)
print(f"Number of days with steps > 8000: {len(filtered_steps)}")



ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()